### ISSUE TITLE
Ligh

### ISSUE THREAD

**Issue by badcat** [LukyVj/colofilter.css#10]
Love this thing!

Typos (5 I think)  for _ligh_ to _light_ in SCSS and resulting CSS file.

e.g. 
 &[class_="-ligh"] {
should be
 &[class_="-light"] {

thanks!

Also - most of these now work in current version of Safari 9.0.2

**Comment by LukyVj** [comment]
Hello! 

You sir, got keen eyes! 
I'll fix it asap!

Yeah I'm aware of this problem, reffers to the documentation on the compatibility section.
A polyfill is on it's way!

**Comment by badcat** [comment]
>^. .^<
(er didn't mean to close)

**Comment by LukyVj** [comment]
Fixed in #11
