### ISSUE TITLE
Use *= instead of ^=

### ISSUE THREAD

**Issue by jamesfzhang** [LukyVj/colofilter.css#16]
You use `[class^="blend"]` everywhere. That requires an element's class to start with "blend". So `<div class="img-container blend-blue">` wouldn't work.

**Comment by LukyVj** [comment]
Yes, so use `blend-blue img-container`. 

---

No, I won't use the `*=` instead of `^=`
If a class contains the word "blend" it will fuck up the style. 

It's safer to target all occurences starting with blend.

**Comment by jamesfzhang** [comment]
Maybe there's another way? It just seems like a weird requirement that class names MUST start with "blend". If you want to dynamically add blend class names for animation and other effects, then it gets pretty ugly.

**Comment by LukyVj** [comment]
Feel free to send a PR, you can target them with a data-attribute if you want, seems cleaner. 

`[data-blend] { // css }`
