### ISSUE TITLE
Support for background image?

### ISSUE THREAD

**Issue by surjithctly** [LukyVj/colofilter.css#17]
I was pretty excited to see this.. because I wanted this effect in a recent project. But unfortunately, there no background image support? 

Please make an option to work with on background images also? I'm not sure its possible, but please let me know.

Keep up the great work!

~Surjith

**Comment by LukyVj** [comment]
Hey Surjith!

Thanks a lot for opening this issue! 
So yeah, basically, it would be possible to make it work with background images, I hesitated but since you ask for it I think it could be a good thing to add to colofilter.

I'll update the project version as soon as I have a little bit of spare time.

Keeping you updated :)

Lucas.

**Comment by surjithctly** [comment]
Oh! Thank you Lucas,

I'll be keeping an eye on it.. This is what my[ design look like](https://dribbble.com/shots/2385358-Music-Band-Website-Sneak-Peek). 

~Surjith

**Comment by LukyVj** [comment]
Yeah :) it should work !

**Comment by LukyVj** [comment]
Hello @surjithctly ! 

So, here is a workaround about making colofilter.css work with background image: 
http://codepen.io/LukyVj/pen/9a44a89dc4e49884347141bb74a8927f?editors=0100

I will update the library as soon as I have some free time. 
Meanwhile, you can use my workaround as base. 

Tell me if you need the code to be commented :)

**Comment by surjithctly** [comment]
Hello,

But seems I can't put text in inside.. It will messup the layout..

I have a codepen, can you try with that? http://codepen.io/surjithctly/pen/QyeNVv

Thanks for your time.

~Surjith

**Comment by LukyVj** [comment]
I think you have to put the text on an other container, with an absolute position.
