### ISSUE TITLE
Some questions about version and license

### ISSUE THREAD

**Issue by kennynaoh** [LukyVj/colofilter.css#19]
Hello @LukyVj ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
Please help us add git tag.
Git tag can help us to know your release version.
And I also want to know which version do you use.
You could take a look at [this](https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json).
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/7826

**Comment by LukyVj** [comment]
Hey, thanks for your issue.
I will do it asap.

**Comment by LukyVj** [comment]
Meanwhile if you want to add Family.scss to CDNJS, you can check https://github.com/LukyVj/family.scss

There is both license and tags.

**Comment by kennynaoh** [comment]
Maybe you could remind me after you fix that.
Thanks very much!

**Comment by LukyVj** [comment]
Closed with 96d7735

**Comment by LukyVj** [comment]
All good @kennynaoh
